# Generated by Django 6.0.7 on 2026-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
