# Generated by Django 6.0.7 on 2026-07-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='name',
        ),
    ]
