# Generated by Django 6.0.7 on 2026-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_first_name_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Computer Science', 'CS'), ('Mathematics', 'MATH'), ('Physics', 'PHY'), ('Chemistry', 'CHE'), ('Biology', 'BIO'), ('Engineering', 'ENG'), ('Business', 'BUS'), ('Literature', 'LIT'), ('History', 'HIST'), ('Art', 'ART')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
